<?php
// Auto-generated by proxmox/install-lxc.sh from proxmox/init.template.php.
// Placeholders are replaced at install time. Edit values directly here if you
// need to change DB credentials, cookie/session names, or ANSIBLE_PATH.

define('USERSPICE_ACTIVE_LOGGING', false);
$noPHPInfo = false;
require_once 'classes/class.autoloader.php';

ini_set('session.cookie_httponly', 1);
ini_set('session.cookie_samesite', 'Lax');

if (Server::get('HTTPS') !== '' && Server::get('HTTPS') !== 'off') {
	ini_set('session.cookie_secure', 1);
}
session_start();

define('EXTRA_CURL_SECURITY', true);

$abs_us_root = Server::get('DOCUMENT_ROOT');
$self_path = explode("/", Server::get('PHP_SELF'));
$self_path_length = count($self_path);
$file_found = FALSE;

for ($i = 1; $i < $self_path_length; $i++) {
	array_splice($self_path, $self_path_length - $i, $i);
	$us_url_root = implode("/", $self_path) . "/";

	if (file_exists($abs_us_root . $us_url_root . 'z_us_root.php')) {
		$file_found = TRUE;
		break;
	} else {
		$file_found = FALSE;
	}
}

require_once $abs_us_root . $us_url_root . 'users/helpers/helpers.php';

$GLOBALS['config'] = array(
	'mysql' => array(
		'force_utc_mysql' => false,
		'charset'         => 'utf8mb4',
		'host'            => 'localhost',
		'username'        => 'root',
		'password'        => '__MYSQL_PASSWORD__',
		'db'              => '__DB_NAME__',
		'port'            => '3306',
	),
	'remember' => array(
		'cookie_name'   => '__COOKIE_NAME__',
		'cookie_expiry' => 604800,
	),
	'session' => array(
		'session_name' => '__SESSION_NAME__',
		'token_name'   => 'token',
	)
);

// Path to the Ansible playbooks directory. The web UI's exec helper uses this
// as the cwd for every ansible-playbook invocation.
define('ANSIBLE_PATH', '__ANSIBLE_PATH__');

$db_table_prefix = "uc_";
$master_account = [1];

$currentPage = currentPage();

if (Cookie::exists(Config::get('remember/cookie_name')) && !Session::exists(Config::get('session/session_name'))) {
	$hash = Cookie::get(Config::get('remember/cookie_name'));
	$hashCheck = DB::getInstance()->query("SELECT * FROM users_session WHERE hash = ? AND uagent = ?", array($hash, Session::uagent_no_version()));

	if ($hashCheck->count()) {
		$user = new User($hashCheck->first()->user_id);
		$inst = Config::get('session/session_name');
		$_SESSION[$inst . '_login_method'] = "cookie";
		$user->login();
	}
}

$user = new User();

if ($user->isLoggedIn()) {
	$verifySkipPages = ['verify.php', 'logout.php', 'verify_thankyou.php', 'verify_resend.php'];
	if ($user->data()->email_verified == 0 && !in_array($currentPage, $verifySkipPages)) {
		Redirect::to($us_url_root . 'users/verify.php');
	}
}

$timezone_string = 'America/New_York';
date_default_timezone_set($timezone_string);

$userspice_nonce = base64_encode(random_bytes(16));
require_once $abs_us_root . $us_url_root . "users/includes/loader.php";
